version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    network_mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongodb_password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: